### ISSUE TITLE
resx file not recognized correctly

### ISSUE THREAD

**Issue by CyberGuerro** [Dspecht7123/ASP.NETCoreLocalizationResourceFileManger#1]
I have a .Net project and views are organized like this:
**Views\ViewName\index.cshtml**

Their localizations are organized like this:
**Resources\Views\ViewName.Index.[language code (es. "en") or nothing for natural].resx**

In this case it doesn't recognize all localizations, but only considers up to **".Index"**

For controllers, resource files are organized like this:
**Resources\Controllers\ControllerName.string.[language code (es. "en") or nothing for natural].resx**

In this case it doesn't recognize all localizations but only considers up to **"string"**

**Comment by Dspecht7123** [comment]
Hello @CyberGuerro ,
thanks for reporting the issue. I will have a look the following days.

**Comment by Dspecht7123** [comment]
Hello @CyberGuerro ,
I have changed the logic for recognizing the resx-files.
Please let me know if the issue is fixed for you. If yes I will close the issue.

**Comment by CyberGuerro** [comment]
THX, I’ll test it on monday when I’ll come back from holydays 😀
Stay tuned

**Comment by CyberGuerro** [comment]
With 0.0.6 now it works like a charm :-)
Good job

**Comment by Dspecht7123** [comment]
Great!
@CyberGuerro if you like the extension I'm happy about a rating in the marketplace
