### ISSUE TITLE
Keys with empty value added

### ISSUE THREAD

**Issue by dellabellacitta** [Dspecht7123/ASP.NETCoreLocalizationResourceFileManger#3]
If I open a .resx structure, where a localized resource doesn't contain values for all keys, upon saving in Resource Manager, the "missing" keys are added without value. Is this on purpose or could it be prevented?

Example: The resource file for a restaurant menu might have a natural version in English (Menu.resx) and a localized version for German (Menu.de.resx). While most of the meals need to be translated, "Pizza Margherita" doesn't need a translation. So the Menu.de.resx simply doesn't contain this entry.
When opening the structure in Resource Manager, the field is empty. I leave it empty.
Upon saving, however, Menu.de.resx will contain something like this:

```
  <data name="PizzaMargherita" xml:space="preserve">
    <value/>
  </data>
```

I would prefer not having this element added. Would this be possible?

**Comment by Dspecht7123** [comment]
Hello @dellabellacitta ,
the new version of the extension is online.
Keys with empty values are not added anymore.
Please verify if the issue is solved.

Regards,
David

**Comment by dellabellacitta** [comment]
Hello @Dspecht7123,
thank you for the new version.
I confirm that empty values are not added anymore :-)

However, existing values get deleted if they are not contained in all files :-(
In the above example, "Pizza Margherita" would be deleted from the natural version (Menu.resx).

In my case, I have English text in a .resx file, a rudimentary translation (leaving many labels untranslated) in a .fr.resx file, a German translation in a .de.resx file, and a "gendered" German version (with only some labels different than the base German version) in a .de-DE-Gender.resx file. So the gendered-German file and the French file contain much less values, making the software fall back to the base German and the natural (English) values, respectively. I think this is how the resource localization was intended to be used.

What I've done: I've opened a resource and, without changing anything, saved the resource. Ideally, this would not result in any change to the files. No value should be deleted and no empty value added. Is this possible?

**Comment by Dspecht7123** [comment]
Hello @dellabellacitta,

Unfortunately, I could not reproduce this issue on my system.
Could you please provide example-files where this behaviour is happening?

**Comment by dellabellacitta** [comment]
Hello @Dspecht7123,
I hope I'm not causing too much work on your side. Thank you for staying with this!

[Resources.zip](https://github.com/Dspecht7123/ASP.NETCoreLocalizationResourceFileManger/files/13217681/Resources.zip)
I have attached an archive with 4 files of resource "Benutzer".
If I open them with Resource Manager (v0.0.9 in Code - OSS 1.83.1) and, without changing anything, click "Save", all 4 files get modified.
In Benutzer.de-DE-Gender.resx, the change only cuts some whitespace (created by some other tool) and adds empty comment tags (see issue #2). However, in Benutzer.resx, there are more changes.

Looking at it again, it seems that entries are in a different order. (Sorry for claiming them deleted in an earlier comment. I had not scrolled down completely.) Some entries are missing from where they used to be and added at the end.
Could it be that all entries from Benutzer.resx, which are not contained in Benutzer.de-DE-Gender.resx, are added at the end?

This would be less severe than loosing content, of course.
But still I would like to preserve as much as possible of the file structure. As far as I know, these files are created and amended in development using some other tooling. Keys are in alphabetical order, and I've noticed them getting re-ordered alphabetically with every touch by that other tooling. Since a constant restructuring makes it difficult tracing changes during distributed development, and since I cannot influence the workings of that other tooling,
I would like Resource Manager to either keep the existing file structure or align with that other tooling and save keys in alphabetical order.

Can you confirm my analysis (entries not existing in one file get moved to the end of other files)?
Would it be possible to keep the order of keys or to treat them alphabetically?

**Comment by Dspecht7123** [comment]
Hello @dellabellacitta ,

Thanks for the detailed explanation.
There is a new version on OpenVSX.

I am using a library for reading and writing to the .resx - files. This library changed the order of the entries. 
I changed it a little and now the entries get sorted with the Array.prototype.sort() method (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) which sorts them alphabetically. However, the order of entries still gets changed a little. Would this be acceptable for you?

Empty comments should not be added automatically anymore.

**Comment by Dspecht7123** [comment]
@dellabellacitta , if you like the extension I'm happy if you rate it
