### ISSUE TITLE
Consider resources for unusual locales

### ISSUE THREAD

**Issue by dellabellacitta** [Dspecht7123/ASP.NETCoreLocalizationResourceFileManger#4]
I maintain German and Italian translations for a little project. Developers have come up with an unusual locale: de-DE-Gender. (You might understand where this comes from; it contains values like "Nutzer*in"...)
So there is, for example, this file list for resource _Reports_:
- _Reports.resx_
- _Reports.fr.resx_
- _Reports.it.resx_
- _Reports.de.resx_
- _Reports.de-DE-Gender.resx_

Resource Manager offers me to open path "Reports" and "Reports.de-DE-Gender". The former will open the first 4 files, while the latter will open the fifth file. I would like Resource Manager to recognize _Reports.de-DE-Gender.resx_ as a localization of _Resource.resx_ and open all 5 files for path "Reports".

Would this be possible?

**Comment by Dspecht7123** [comment]
Hello @dellabellacitta ,

thanks for reporting the issue.

Currently, Resource Manager only recognizes standard language-codes which consist of two characters for the language and two characters for the culture separated by a minus like this: "de-de" or "en-uk"
I don't plan to change this behaviour as I don't know how to detect the language afterwards.

However, for your special case I could implement the following:
Resource-Manager reads the custom language-codes from a JSON-File. So you would need to add a JSON-File in your root-resource-folder which looks for example like this: 
`{
    "customLanguageCodes": [
        "de-de-Gender"
    ]
}`

Or I could add a setting to the extension where you can add the custom language codes.

Would this solve your problem?

**Comment by dellabellacitta** [comment]
Hello @Dspecht7123 ,

thank you for looking into my issue..
I think, both your ideas (JSON file or extension setting) for introducing a custom language code would solve my special problem here.
I'd prefer the extension setting, as it is easier to handle for me.

**Comment by Dspecht7123** [comment]
I also prefer the extension setting
I think I will be able to work on the issues next week

**Comment by Dspecht7123** [comment]
Hello @dellabellacitta ,
the new version of the extension is online.
Please verify if the issue is solved.

Regards,
David

**Comment by dellabellacitta** [comment]
Thank you, @Dspecht7123!
As I am using Code - OSS with the [Open VSX](https://open-vsx.org/) registry, could you please [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) version 0.0.9 there?

**Comment by Dspecht7123** [comment]
@dellabellacitta 
Oh sorry, I forgot to do that.
The new version is now available on Open VSX too.

**Comment by dellabellacitta** [comment]
@Dspecht7123, thank you for publishing to Open VSX -- and for adding the setting to include the special language code!
